# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - release
  - devel
  - oldrel

matrix:
  allow_failures:
    - r: devel
    - r: oldrel

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
